---
name: Esoteric
author: ethaniccc
description: A private anti-cheat made for PocketMine-MP
version: 1.1.0
main: ethaniccc\Esoteric\Loader
api: 3.16.0
mcpe-protocol:
  - 419
  - 422
  - 428
permissions:
  ac:
    description: Gives all anticheat permissions
    default: op
    children:
      ac.alerts:
        description: Gives access to anticheat alerts
        default: op
      ac.bypass:
        description: Allows to bypass anticheat punishments
        default: op
      ac.command:
        description: Allows for all usages of the anticheat command
        default: op
        children:
          ac.command.help:
            description: Access to the anticheat's help command
            default: op
          ac.command.logs:
            description: Access to get the anticheat logs of a player
            default: op
          ac.command.delay:
            description: Access to change the alert delay
...
